require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false
